import { StyleSheet } from "react-native";

const estilosProd = StyleSheet.create({
    corFundo: {
        backgroundColor: "#111111",
        paddingBottom: 50,
    },
    headerContainer: {
        width: "100%",
        height: 350,
        position: "relative",
        justifyContent: "center",
        alignItems: "center",
    },
    headerLogo: {
        width: 300,
        height: 300,
        alignSelf: "center",
        zIndex: 1,
    },
    headerText: {
        color: "white",
        fontSize: 24,
        fontFamily: 'FontePadraoBold',
        marginTop: 12,
        textAlign: "center",
    },
    listContent: {
        paddingBottom: 40,
    },
    card: {
        width: "90%",
        marginVertical: 10,
        alignSelf: "center",
        borderRadius: 20,
        overflow: "hidden",
        borderWidth: 1,
        borderColor: "#6d24ca",
        backgroundColor: "#1b1b1b",
        elevation: 4,
    },
    cardContent: {
        paddingBottom: 16,
        paddingHorizontal: 16,
        backgroundColor: "#1b1b1b",
    },
    nome: {
        color: "#ffffff",
        fontSize: 20,
        fontFamily: 'FontePadraoBold',
        marginBottom: 8,
        textAlign: 'left',
        alignSelf: 'flex-start',
    },
    descricao: {
        color: '#d0d0d0',
        fontSize: 16,
        lineHeight: 24,
        textAlign: 'left',
        alignSelf: 'flex-start',
    },
    cardCover: {
        height: 180,
        backgroundColor: "#2a2a2a",
    },
    cardActions: {
        justifyContent: 'flex-start',
        paddingBottom: 12,
    },
    botaoDetalhes: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 16,
        paddingVertical: 8,
        backgroundColor: '#6d24ca',
        borderRadius: 8,
        gap: 8,
    },
    textoDetalhes: {
        color: '#ffffff',
        fontSize: 14,
        fontWeight: '600',
    },
    modalContainer: {
        flex: 1,
        backgroundColor: '#111111',
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingTop: 40,
    },
    modal: {
        flex: 1,
        width: '90%',
        backgroundColor: '#1b1b1b',
        borderRadius: 16,
        overflow: 'hidden',
        paddingHorizontal: 20,
        paddingVertical: 20,
    },
    modalContent: {
        alignItems: 'center',
        paddingBottom: 40,
    },
    carrosselContainer: {
        width: 280,
        height: 280,
        marginBottom: 20,
        marginTop: 20,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: '#2a2a2a',
    },
    imagemCarrossel: {
        width: 280,
        height: 280,
    },
    indicadores: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 24,
        gap: 8,
    },
    ponto: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#666',
    },
    pontoBrilho: {
        backgroundColor: '#6d24ca',
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    botaoModal: {
        position: 'absolute',
        top: 16,
        right: 16,
        zIndex: 10,
        padding: 8,
        backgroundColor: 'rgba(109, 36, 202, 0.7)',
        borderRadius: 50,
    },
    imagemModal: {
        width: 280,
        height: 280,
        marginBottom: 24,
        marginTop: 20,
        borderRadius: 12,
    },
    nomeServico: {
        color: '#ffffff',
        fontSize: 24,
        fontFamily: 'FontePadraoBold',
        marginBottom: 16,
        textAlign: 'center',
    },
    descServico: {
        color: '#d0d0d0',
        fontSize: 16,
        lineHeight: 24,
        textAlign: 'center',
        paddingHorizontal: 12,
    },
    badgeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        backgroundColor: 'rgba(109, 36, 202, 0.28)',
        borderWidth: 1,
        borderColor: 'rgba(109, 36, 202, 0.6)',
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 4,
        marginBottom: 40,
        marginTop: 12,
        gap: 6,
    },
    badgeTexto: {
        color: '#ffffff',
        fontSize: 12,
        fontWeight: '600',
    },
    textoContato: {
        color: '#ffffff',
        fontSize: 12,
        fontWeight: '600',
    },
    botaoContatoCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        backgroundColor: '#25D366',
        borderRadius: 8,
        gap: 6,
    },
    badgeContainerModal: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'center',
        backgroundColor: 'rgba(109, 36, 202, 0.28)',
        borderWidth: 1,
        borderColor: 'rgba(109, 36, 202, 0.6)',
        borderRadius: 16,
        paddingHorizontal: 14,
        paddingVertical: 6,
        marginTop: 12,
        marginBottom: 16,
        gap: 6,
    },
    badgeTextoModal: {
        color: '#ffffff',
        fontSize: 13,
        fontWeight: '600',
    },
    secaoDetalhes: {
        backgroundColor: '#252525',
        borderLeftWidth: 3,
        borderLeftColor: '#6d24ca',
        paddingHorizontal: 16,
        paddingVertical: 12,
        marginHorizontal: 12,
        marginTop: 16,
        marginBottom: 16,
        borderRadius: 8,
    },
    secaoTitulo: {
        color: '#a855f7',
        fontSize: 11,
        fontWeight: '700',
        textTransform: 'uppercase',
        marginBottom: 8,
        letterSpacing: 0.8,
    },
    secaoTexto: {
        color: '#e0e0e0',
        fontSize: 14,
        lineHeight: 22,
    },
    infoGrid: {
        marginHorizontal: 0,
        marginTop: 8,
        marginBottom: 16,
        gap: 10,
        paddingHorizontal: 12,
    },
    infoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#252525',
        borderRadius: 8,
        gap: 100,
    },
    infoIconLabel: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    infoLabel: {
        color: '#888888',
        fontSize: 12,
        fontWeight: '600',
    },
    infoValor: {
        color: '#e0e0e0',
        fontSize: 14,
        fontWeight: '500',
        marginLeft: 'auto',
    },
    botaoContatoModal: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#25D366',
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 14,
        marginHorizontal: 12,
        marginTop: 12,
        marginBottom: 20,
        gap: 10,
    },
    textoContatoModal: {
        color: '#ffffff',
        fontSize: 15,
        fontWeight: '600',
    },
})

export default estilosProd;