import { StyleSheet } from "react-native";

const estilosProd = StyleSheet.create({
    corFundo: {
        backgroundColor: "#111111",
        paddingBottom: 50,
    },
    headerContainer: {
        width: "100%",
        height: 350,
        position: "relative",
        justifyContent: "center",
        alignItems: "center",
    },
    headerLogo: {
        width: 300,
        height: 300,
        alignSelf: "center",
        zIndex: 1,
    },
    headerText: {
        color: "white",
        fontSize: 24,
        fontWeight: "700",
        marginTop: 12,
        textAlign: "center",
    },
    listContent: {
        paddingBottom: 40,
    },
    card: {
        width: "90%",
        marginVertical: 10,
        alignSelf: "center",
        borderRadius: 20,
        overflow: "hidden",
        borderWidth: 1,
        borderColor: "#6d24ca",
        backgroundColor: "#1b1b1b",
        elevation: 4,
    },
    cardContent: {
        paddingBottom: 16,
        paddingHorizontal: 16,
        backgroundColor: "#1b1b1b",
    },
    nome: {
        color: "#ffffff",
        fontSize: 20,
        fontWeight: "700",
        marginBottom: 8,
    },
    descricao: {
        color: "#d0d0d0",
        fontSize: 16,
        lineHeight: 24,
    },
    cardCover: {
        height: 180,
        backgroundColor: "#2a2a2a",
    },
    cardActions: {
        justifyContent: 'center',
        paddingBottom: 12,
    },
    botaoDetalhes: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 16,
        paddingVertical: 8,
        backgroundColor: '#6d24ca',
        borderRadius: 8,
        gap: 8,
    },
    textoDetalhes: {
        color: '#ffffff',
        fontSize: 14,
        fontWeight: '600',
    },
    modalContainer: {
        flex: 1,
        backgroundColor: '#111111',
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingTop: 40,
    },
    modal: {
        flex: 1,
        width: '90%',
        backgroundColor: '#1b1b1b',
        borderRadius: 16,
        overflow: 'hidden',
        paddingHorizontal: 20,
        paddingVertical: 20,
    },
    modalContent: {
        alignItems: 'center',
        paddingBottom: 40,
    },
    carrosselContainer: {
        width: 280,
        height: 280,
        marginBottom: 20,
        marginTop: 20,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: '#2a2a2a',
    },
    imagemCarrossel: {
        width: 280,
        height: 280,
    },
    indicadores: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 24,
        gap: 8,
    },
    ponto: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#666',
    },
    pontoBrilho: {
        backgroundColor: '#6d24ca',
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    botaoModal: {
        position: 'absolute',
        top: 16,
        right: 16,
        zIndex: 10,
        padding: 8,
        backgroundColor: 'rgba(109, 36, 202, 0.7)',
        borderRadius: 50,
    },
    imagemModal: {
        width: 280,
        height: 280,
        marginBottom: 24,
        marginTop: 20,
        borderRadius: 12,
    },
    nomeServico: {
        color: '#ffffff',
        fontSize: 24,
        fontWeight: '700',
        marginBottom: 16,
        textAlign: 'center',
    },
    descServico: {
        color: '#d0d0d0',
        fontSize: 16,
        lineHeight: 24,
        textAlign: 'center',
        paddingHorizontal: 12,
    },
})

export default estilosProd;