import { StyleSheet } from 'react-native';

const estilosPerfil = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111111',
  },
  content: {
    paddingBottom: 40,
  },
  headerContainer: {
    width: '100%',
    height: 220,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
  },
  headerBackground: {
    width: 220,
    height: 220,
    opacity: 0.16,
  },
  cameraContainer: {
    width: '90%',
    height: 200,
    alignSelf: 'center',
    marginTop: 20,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#6d24ca',
    backgroundColor: '#1b1b1b',
  },
  camera: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    paddingTop: 12,
    paddingRight: 12,
  },
  cameraVirarBotao: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#6d24ca',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#6d24ca',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  cardContainer: {
    width: '90%',
    marginVertical: 20,
    alignSelf: 'center',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#6d24ca',
    backgroundColor: '#1b1b1b',
    padding: 16,
  },
  photoWrapper: {
    width: 160,
    height: 160,
    borderRadius: 100,
    backgroundColor: '#1a1a1a',
    alignSelf: 'center',
    marginTop: -80,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  photo: {
    width: 140,
    height: 140,
    borderRadius: 70,
  },
  cameraButton: {
    position: 'absolute',
    right: 4,
    bottom: 4,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#6d24ca',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#111111',
  },
  sectionTitle: {
    color: 'white',
    fontSize: 24,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 24,
    marginBottom: 16,
  },
  form: {
    paddingHorizontal: 24,
  },
  label: {
    color: '#f5f5f5',
    fontSize: 16,
    textAlign: 'left',
    marginBottom: 6,
    marginTop: 16,
  },
  input: {
    width: '100%',
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#333',
    backgroundColor: '#1d1d1d',
    color: 'white',
    paddingHorizontal: 16,
  },
  inputDisabled: {
    backgroundColor: '#161616',
    borderColor: '#2a2a2a',
    color: '#999',
  },
  text: {
    color: '#ffffff',
    fontSize: 16,
    textAlign: 'center',
  },
  message: {
    color: '#d0d0d0',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 16,
  },
  button: {
    width: '100%',
    height: 54,
    borderRadius: 14,
    backgroundColor: '#6d24ca',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 32,
    marginBottom: 16,
    shadowColor: '#6d24ca',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    flexDirection: 'row',
    gap: 8,
  },
  buttonGroup: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 32,
  },
  buttonSalvar: {
    flex: 1,
    backgroundColor: '#6d24ca',
  },
  buttonCancelar: {
    flex: 1,
    backgroundColor: '#444',
    shadowColor: '#000',
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  cameraPermissionText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
});

export default estilosPerfil;
